export const ListComments = [
    {
        id:1,
        avt:'/image/avtUser.jpg',
        authorName:'nguyen ngoc duy',
        timePost:'3 day ago',
        rateComment:2,
        contentComment:'Bầu trời xanh, làn mây trắng. Anh yêu nắng hay yêu em?',
    },
    {
        id:2,
        avt:'/image/avtUser.jpg',
        authorName:'nguyen thanh long',
        timePost:'4 day ago',
        rateComment:2,
        contentComment:'Nhờ có nắng mới thấy cầu vồng. Nhờ có anh mới thấy màu hạnh phúc.',
    },
    {
        id:3,
        avt:'/image/avt2User.jpg',
        authorName:'nguyen ba huy',
        timePost:'11 day ago',
        rateComment:2,
        contentComment:'Trước khi gặp được anh thì chẳng có ai, sau khi gặp anh thì không muốn có thêm ai nữa.',
    },
    {
        id:4,
        avt:'/image/avt3User.jpg',
        authorName:'luu van hoang',
        timePost:'2 day ago',
        rateComment:2,
        contentComment:'Soái ca là của ngôn tình. Còn anh thì chỉ của mình em thôi.',
    },
    {
        id:5,
        avt:'/image/avt4.jpg',
        authorName:'Dao Thi Thanh Thao',
        timePost:'1 day ago',
        rateComment:0,
        contentComment:'Giữa cuộc đời hàng ngàn cám dỗ. Em chỉ cần bến đỗ anh thôi.',
    },
    {
        id:6,
        avt:'/image/avt5.jpg',
        authorName:'Dao Thi Hue ',
        timePost:'1 day ago',
        rateComment:2,
        contentComment:'Bồ công anh bay khi có gió. Em chỉ cười vì ở đó có anh.',
    },
    {
        id:7,
        avt:'/image/avt6.jpg',
        authorName:'Dang Thi Thuyet',
        timePost:'1 day ago',
        rateComment:0,
        contentComment:'ủa alo, phải vậy không thế',
    },
    {
        id:8,
        avt:'/image/avt7.jpg',
        authorName:'do van bac',
        timePost:'15 day ago',
        rateComment:2,
        contentComment:'ghê z',
    },
    {
        id:9,
        avt:'/image/avt4.jpg',
        authorName:'pham thanh long',
        timePost:'12 day ago',
        rateComment:2,
        contentComment:' Ai nào cho mượn avatar để em đỡ cô đơn đi',
    },
    {
        id:10,
        avt:'/image/avt4.jpg',
        authorName:'la van phuc',
        timePost:'19 day ago',
        rateComment:0,
        contentComment:'đỉnh quá vậy em zai',
    },
    {
        id:11,
        avt:'/image/avt4.jpg',
        authorName:'trinh duy hung',
        timePost:'17 day ago',
        rateComment:2,
        contentComment:'GoodJob em oi',

    }
];